AWSTemplateFormatVersion: '2010-09-09'
Description: Configuración de usuarios y grupos IAM para roles organizativos básicos

Resources:

  # === Grupos ===
  SecurityViewersGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: SecurityViewers

  DevOpsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: DevOps

  ComplianceGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Compliance

  AdminCloudGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: AdminCloud

  # Politica de admin en Security Hub para AdminCloudGroup 
  AdminCloudPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AdminCloudPolicy
      Groups: [ !Ref AdminCloudGroup ]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - securityhub:*
              - iam:*
              - config:*
              - cloudtrail:*
              - guardduty:*
              - kms:*
              - organizations:Describe*
              - organizations:List*
            Resource: "*"

  # Politica de solo lectura en Security Hub 

  SecurityHubViewerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: SecurityHubViewerPolicy
      Groups:
        - !Ref SecurityViewersGroup
        - !Ref DevOpsGroup
        - !Ref ComplianceGroup
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - securityhub:GetFindings
              - securityhub:DescribeStandards
              - securityhub:GetInsightResults
              - securityhub:GetAdhocInsightResults
              - securityhub:DescribeHub
              - securityhub:ListEnabledProductsForImport
              - securityhub:ListFindingAggregators
              - securityhub:ListMembers
            Resource: "*"

  # === Usuarios (2 por grupo) ===

  # SecurityViewers
  SecurityUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: securityviewer-user1
      Groups: [ !Ref SecurityViewersGroup ]
      LoginProfile:
        Password: 'Password123!' 
        PasswordResetRequired: true

  SecurityUser2:
    Type: AWS::IAM::User
    Properties:
      UserName: securityviewer-user2
      Groups: [ !Ref SecurityViewersGroup ]
      LoginProfile:
        Password: 'Password123!' 
        PasswordResetRequired: true

  # DevOps
  DevOpsUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: devops-user1
      Groups: [ !Ref DevOpsGroup ]
      LoginProfile:
        Password: 'Password123!' 
        PasswordResetRequired: true

  DevOpsUser2:
    Type: AWS::IAM::User
    Properties:
      UserName: devops-user2
      Groups: [ !Ref DevOpsGroup ]
      LoginProfile:
        Password: 'Password123!' 
        PasswordResetRequired: true

  # Compliance
  ComplianceUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: compliance-user1
      Groups: [ !Ref ComplianceGroup ]
      LoginProfile:
        Password: 'Password123!' 
        PasswordResetRequired: true

  ComplianceUser2:
    Type: AWS::IAM::User
    Properties:
      UserName: compliance-user2
      Groups: [ !Ref ComplianceGroup ]
      LoginProfile:
        Password: 'Password123!' 
        PasswordResetRequired: true

  # AdminCloud
  AdminUser1:
    Type: AWS::IAM::User
    Properties:
      UserName: admincloud-user1
      Groups: [ !Ref AdminCloudGroup ]
      LoginProfile:
        Password: 'Password123!' 
        PasswordResetRequired: true

  AdminUser2:
    Type: AWS::IAM::User
    Properties:
      UserName: admincloud-user2
      Groups: [ !Ref AdminCloudGroup ]
      LoginProfile:
        Password: 'Password123!' 
        PasswordResetRequired: true

