AWSTemplateFormatVersion: '2010-09-09'
Description: Prerrequisitos de despliegue - Usuario github-deploy con permisos especificos para automatizacion 

Parameters:
  OrgId:
    Type: String
    Description: ID de la organizacion AWS 

  AuditBucketName:
    Type: String
    Description: Nombre del bucket S3 central de auditoria y logs

Resources:

  GitHubDeployUser:
    Type: AWS::IAM::User
    Properties:
      UserName: github-deploy
      Policies:
        - PolicyName: GitHubDeployPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: SecurityHubOperations
                Effect: Allow
                Action:
                  - securityhub:EnableSecurityHub
                  - securityhub:BatchEnableStandards
                  - securityhub:DescribeHub
                  - securityhub:DescribeStandards
                  - securityhub:GetFindings
                  - securityhub:GetEnabledStandards
                  - securityhub:ListMembers
                  - securityhub:GetAdhocInsightResults
                  - securityhub:ListFindingAggregators
                Resource: '*'
              - Sid: IAMForAutomation
                Effect: Allow
                Action:
                  - iam:CreateUser
                  - iam:CreateGroup
                  - iam:AddUserToGroup
                  - iam:PutGroupPolicy
                  - iam:ListGroups
                  - iam:ListUsers
                  - iam:GetUser
                  - iam:CreateLoginProfile
                Resource: '*'

  GitHubDeployAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref GitHubDeployUser
      Status: Active
  ##  Clave KMS 
  TrailKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Clave KMS para cifrado
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: RootAccess
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: '*'
          - Sid: AllowCloudTrail
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action:
              - kms:GenerateDataKey*
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
            Resource: '*'
            Condition:
              StringEquals:
                kms:EncryptionContext:aws:cloudtrail:arn: !Sub arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/OrgTrail
  ##  Bucket S3 central de logs 
  AuditBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref AuditBucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  AuditBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AuditBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowConfigPut
            Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub arn:aws:s3:::${AuditBucketName}/config-logs/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
          - Sid: AllowConfigGetAcl
            Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub arn:aws:s3:::${AuditBucketName}
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub arn:aws:s3:::${AuditBucketName}
          - Sid: AllowCloudTrailPut
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub arn:aws:s3:::${AuditBucketName}/AWSLogs/${AWS::AccountId}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
  CloudTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      TrailName: MyOrganizationTrail
      S3BucketName: !Ref AuditBucket
      IsLogging: true
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
      EnableLogFileValidation: true
      EventSelectors:
        - ReadWriteType: All
          IncludeManagementEvents: true
          DataResources:
            - Type: AWS::S3::Object
              Values:
                - !Sub arn:aws:s3:::${AuditBucketName}/
  ##  AWS Config
  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Properties:
      Name: default
      RoleARN: !GetAtt ConfigRecorderRole.Arn
      RecordingGroup:
        AllSupported: true
        IncludeGlobalResourceTypes: true

  ConfigDeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    Properties:
      S3BucketName: !Ref AuditBucket
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: One_Hour
      S3KeyPrefix: config-logs

  ConfigRecorderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ConfigRecorderRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: ConfigRecorderFullAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - config:Put*
                - config:Get*
                - config:Describe*
                - ec2:Describe*
                - iam:Get*
                - iam:List*
                - s3:Get*
                - s3:List*
                - kms:ListAliases
                - kms:DescribeKey
                - kms:GetKeyRotationStatus
              Resource: '*'
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetBucketAcl
              Resource: !Sub arn:aws:s3:::${AuditBucketName}/config-logs/*
   ##  GuardDuty Detector 
  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true
      FindingPublishingFrequency: FIFTEEN_MINUTES

Outputs:
  GitHubDeployAccessKeyId:
    Description: Access Key ID para el usuario github-deploy
    Value: !Ref GitHubDeployAccessKey
    Export:
      Name: GitHubDeployAccessKeyId

  GitHubDeploySecretAccessKey:
    Description: Secret Access Key para el usuario github-deploy
    Value: !GetAtt GitHubDeployAccessKey.SecretAccessKey
    Export:
      Name: GitHubDeploySecretAccessKey
