securityviewer-user1: ViewerUser123!
securityviewer-user2: ViewerUser123!
devops-user1: DevOpsUser123!
devops-user2: DevOpsUser123!
compliance-user1: ComplianceUser123!
compliance-user2: ComplianceUser123!
admincloud-user1: AdminUser123!
admincloud-user2: AdminUser123!

