Standards:
  - arn:aws:securityhub:eu-west-1::standards/aws-foundational-security-best-practices/v/1.0.0
  - arn:aws:securityhub:::ruleset/cis-aws-foundations-benchmark/v/1.2.0
  - arn:aws:securityhub:eu-west-1::standards/pci-dss/v/3.2.1

